name: Auto Update from Releases

on:
  schedule:
    # 每天UTC时间0点运行（北京时间8点）
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整的git历史记录
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests gitpython
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Run update
      run: python update.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
