name: Auto Update from Releases
on:
  schedule:
    - cron: '0 16 * * *'  # 北京时间0点执行（对应UTC 16点）
  workflow_dispatch:  # 手动触发按钮

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键！赋予 GITHUB_TOKEN 写入仓库内容的权限（否则无法 push）
    steps:
      - uses: actions/checkout@v4  # 必须用 v3+，确保能获取仓库权限
        with:
          fetch-depth: 0  # 获取完整 Git 历史，避免提交冲突
          ref: main  # 明确指定分支（你的仓库默认分支，如 main 或 master）
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 与脚本依赖的 Python 版本一致
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gitpython  # 安装脚本依赖包
      
      - name: Run update script
        run: python update.py  # 执行优化后的脚本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动注入的令牌，无需手动创建
          GITHUB_REPOSITORY: ${{ github.repository }}  # 自动注入仓库名（用户名/仓库名）
